alias proxy_up='export all_proxy=socks5://127.0.0.1:10808'
alias proxy_down='unset all_proxy'
alias v2ray_up='nohup v2ray -c ~/.config/v2ray/CERA.json &> .v2ray/log &'
alias edge='microsoft-edge-dev --proxy-server=socks5://127.0.0.1:10808'
alias gh='history | grep'
alias ..='cd ..'
alias ~='cd ~'
